AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5 # Oldest version kubeclient supports
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 8
Metrics/ModuleLength:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods: [require, raise, include, attr_reader, refute, assert, require_relative]
  Exclude: [Gemfile, Rakefile, kubeclient.gemspec, Gemfile.dev.rb]
Metrics/BlockLength:
  Exclude: [kubeclient.gemspec]
Security/MarshalLoad:
  Exclude: [test/**/*]
Nameing/FileName:
  Exclude: [Gemfile, Rakefile, Gemfile.dev.rb]
Style/RegexpLiteral:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Gemspec/OrderedDependencies:
  Enabled: false
# TODO: enable
Style/FrozenStringLiteralComment:
  Enabled: false
