language: ruby
cache: bundler
script: bundle exec rake $TASK

os:
  - linux
  - osx
rvm:
  - "2.5.0"
  - "2.6.0"
  - "2.7.2"
  - truffleruby-head
env:
 - TASK=test
matrix:
  exclude:
    - os: osx
      rvm: truffleruby-head
  # No point running Rubocop on different rubies, results will be same.
  # The rubies it expects the code to target are controlled in .rubocop.yml.
  include:
    - os: linux
      rvm: "2.5.0"
      env: TASK=rubocop
